/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    KeepAliveWrapper: typeof import('./src/components/KeepAliveWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
