version: '3'

networks:
  frontend:
    external: true

services:
  docker_jenkins:
    user: root
    restart: always
    image: jenkins/jenkins:lts
    container_name: jenkins
    read_only: false
    environment:
      - TZ=Asia/Shanghai
      - 'JENKINS_OPTS=--prefix=/jenkins_home'

    ports:
      - 8080:8080
      - 50000:50000

    volumes:
      - /docker/jenkins_home/:/var/jenkins_home
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose

  docker_nginx_dev:
    restart: always
    image: nginx
    container_name: nginx_dev
    ports:
      - 8001:8001
    volumes:
      - /docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /docker/html:/usr/share/nginx/html
      - /docker/nginx/logs:/var/log/nginx

  docker_nginx_sit:
    restart: always
    image: nginx
    container_name: nginx_sit
    ports:
      - 8002:8002
    volumes:
      - /docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /docker/html:/usr/share/nginx/html
      - /docker/nginx/logs:/var/log/nginx
